### ISSUE TITLE
"Open Task" is rendering only HTML

### ISSUE THREAD

**Issue by Hellsender01** [TFNS/CTFNote#106]
I am getting only HTML while opening `Open Task` Page
![image](https://user-images.githubusercontent.com/57838029/142764390-278d364a-affc-4593-ae62-7d643c2bdf6a.png)

Also, I am getting these warnings while doing `docker-compose up -d`, i guess these warnings are somewhat related to the problem mentioned above.

![image](https://user-images.githubusercontent.com/57838029/142764312-779e6cc6-0b08-482c-b742-7ffa595a54b5.png)

![image](https://user-images.githubusercontent.com/57838029/142764581-ffb497c0-0ad7-4c33-a05d-76512daf1d15.png)

**Comment by JJ-8** [comment]
I think the CSS and JS for Hedgedoc is hosted with a different path than the default path `your.domain.com/pad`. 

Do you use a dedicated (sub)domain for hosting CTFNote? And if you navigate to `/pad`, do you see the Hedgedoc front page? If so, can you check your console and see if the CSS and JS is correctly fetched?

**Comment by Hellsender01** [comment]
No, I have not used any subdomain for [CTFNote](http://redknights.tech), I am getting Hedgedoc front page on /pad but CSS and JS files are not getting fetched.

![image](https://user-images.githubusercontent.com/57838029/142830870-a8291009-d85d-40f4-bc19-5878269c0ff3.png)

**Comment by JJ-8** [comment]
Thank you for sharing your domain and the screenshot.

I think I have found the problem:
![image](https://user-images.githubusercontent.com/34778827/142833158-7f1605a8-b250-4a12-adc7-1f9e5aefd768.png)

This is of course not a valid URL. Have you specified the `CMD_DOMAIN` in the `.env` with `http` in it? If so, can you change it to `CMD_DOMAIN=redknights.tech`?
Also, I would highly suggest to use HTTPS for your hosting since that is supported the best by CTFNote.

**Comment by XeR** [comment]
> Also, I am getting these warnings while doing docker-compose up -d, i guess these warnings are somewhat related to the problem mentioned above.

These errors are "expected".
IIRC we could not make them disappear without introducing vulnerabilities by downgrading the dependencies.

**Comment by Hellsender01** [comment]
Thanks, Issue resolved, http:// was the issue in CMD_DOMAIN
