### ISSUE TITLE
Getting Blank page on HedgeDoc

### ISSUE THREAD

**Issue by Hellsender01** [TFNS/CTFNote#108]
Some players of my team(Not All) including me are facing this problem, We are getting a blank page on HedgeDoc.

![image](https://user-images.githubusercontent.com/57838029/143776205-5d968dc7-f074-4cd7-8008-202e38074342.png)

I guess this may help - 

![image](https://user-images.githubusercontent.com/57838029/143776322-ea4be9f7-2060-4abf-a214-4ee2381b0bf4.png)

**Comment by JJ-8** [comment]
Since some people at your team are experiencing this issue, what browsers are they using?

This issue seems to be in HedgeDoc itself since it doesn't load. Can you check where the `vendors~cover~cover-....js` is located? So is it the JS source of CTFNote or HedgeDoc? If you don't know the answer to this, then sending the full URL to the `.js` file would be helpful.

**Comment by Hellsender01** [comment]
We tried on both Firefox and Chrome, But it doesn't change anything.
Full path for `vendors~cover~cover-....js` - 
https://redknights.tech/pad/build/vendors~index~index-pack~pretty~pretty-pack~slide~slide-pack.8092a5d86578aedd8625.js

**Comment by XeR** [comment]
Your domain uses Cloudflare.
Maybe your teammates are blocked on this specific file and get the "Please stand by, while we are checking your browser..." error message.

**Comment by Hellsender01** [comment]
Yes, it was a cloudflare issue.Disabling cloudflare resolved the issue.

Thanks for your fast responses.
