### ISSUE TITLE
Using typescript for frontend

### ISSUE THREAD

**Issue by theS1LV3R** [TFNS/CTFNote#52]
The frontend is currently using normal JS, which makes development much harder (compared to when using TS).

I could add TS support to the frontend and submit a PR if that is wanted

**Comment by JJ-8** [comment]
@theS1LV3R Please note that if you want to add TS support, you have to work in the `graphql` branch since this branch will be the future for CTFNote. However, as soon as development will be active again here (and my PRs will be merged), I have also a lot of bug fixes and features to merge back into CTFNote from my fork. This could cause a lot of conflicts if you convert it to TS...

**Comment by theS1LV3R** [comment]
Alright, I'll hold back on it. I was working on the `graphql` branch anyways, since it was the most up-to-date.

**Comment by XeR** [comment]
Fixed by 9399a64f0e780a65adef8ea446353b6a4a411ae5
