### ISSUE TITLE
Multiple categories

### ISSUE THREAD

**Issue by XeR** [TFNS/CTFNote#90]
It is not uncommon to have challenges in multiple categories.
For example: reverse + crypto, web + pwn, etc.

The current system allows for a single category.
Filtering by category is awkward

**Comment by JJ-8** [comment]
I did an attempt on implementing this feature: https://github.com/JJ-8/CTFNote/tree/0-tags. If you (or someone else) has time to help testing, that would be greatly appreciated! Unfortunately, due to the big code changes I can't create a PR yet since PRs #210, #212, #213 and #214 should be merged first to sync code with this branch.

**Comment by XeR** [comment]
https://github.com/TFNS/CTFNote/blob/bac4b5c4b97f871ce3203fc577c4e07901311c02/front/src/ctfnote/parsers/justctf.ts#L33-L35

**Comment by JJ-8** [comment]
Closing since this is now fully supported.
